name: CI/CD Pipeline

on:
  push:
    branches: [ "feature/develop/task2" ]
  pull_request:
    branches: [ "feature/develop/task2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest test_1.py -v -s > test_results.txt 2>&1 || true

    - name: Display test results
      run: cat test_results.txt

    - name: Create build artifacts
      run: mkdir -p build

    - name: Copy test results
      run: cp test_results.txt build/test_results.txt

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-results
        path: build/
