# This is a basic workflow to help you get started with Actions
# .github/workflows/build.yml
name: CI/CD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "feature/develop/task2" branch
  push:
    branches: [ "feature/develop/task2" ]
  pull_request:
    branches: [ "feature/develop/task2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest > test_results.txt

    - name: Create build artifacts
      run: mkdir -p build

    - name: Copy test results
      run: cp test_results.txt build/test_results.txt

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-results
        path: build/
